// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGNUP_USER = 'SIGNUP_USER'
export const LOGOUT_USER = 'LOGOUT_USER';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const DELETE_USER = 'DELETE_USER';

// Cooler
export const GET_COOLER = 'GET_COOLER'
export const COOLER_ERROR = 'COOLER_ERROR'
export const COOLER_GET_QUANTITY=  'COOLER_GET_QUANTITY'
export const COOLER_ADD_PRODUCT = 'COOLER_ADD_PRODUCT'
export const COOLER_REMOVE_PRODUCT = 'COOLER_REMOVE_PRODUCT'
export const COOLER_REMOVE_ALL = 'COOLER_REMOVE_ALL'
export const COOLER_CHECKOUT=  'COOLER_CHECKOUT'
export const COOLER_REVIEW = 'COOLER_REVIEW'
export const COOLER_CHECKOUT_AS_GUEST = 'COOLER_CHECKOUT_AS_GUEST'
export const COOLER_CHECKOUT_AS_MEMBER = 'COOLER_CHECKOUT_AS_MEMBER'
export const COOLER_PLACE_ORDER = 'COOLER_PLACE_ORDER'
export const COOLER_REMOVE_ALL = 'COOLER_REMOVE_ALL'
export const COOLER_UPDATE_QUANTITY = 'COOLER_UPDATE_QUANTITY'

// Orders
export const CLEAR_ORDERS
export const LOAD_CURRENT_ORDER

// Products

// Profile
export const CLEAR_PROFILE=  'CLEAR_PROFILE';

