// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const DELETE_USER = 'DELETE_USER';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

// Cooler
export const GET_COOLER = 'GET_COOLER';
export const COOLER_ERROR = 'COOLER_ERROR';
export const COOLER_GET_QUANTITY = 'COOLER_GET_QUANTITY';
export const COOLER_ADD_PRODUCT = 'COOLER_ADD_PRODUCT';
export const COOLER_REMOVE_PRODUCT = 'COOLER_REMOVE_PRODUCT';
export const COOLER_REMOVE_ALL = 'COOLER_REMOVE_ALL';
export const COOLER_CHECKOUT = 'COOLER_CHECKOUT';
export const COOLER_REVIEW = 'COOLER_REVIEW';
export const COOLER_CHECKOUT_AS_GUEST = 'COOLER_CHECKOUT_AS_GUEST';
export const COOLER_CHECKOUT_AS_MEMBER = 'COOLER_CHECKOUT_AS_MEMBER';
export const COOLER_PLACE_ORDER = 'COOLER_PLACE_ORDER';
export const COOLER_UPDATE_QUANTITY = 'COOLER_UPDATE_QUANTITY';
export const COOLER_ADDRESS_VALID = 'COOLER_ADDRESS_VALID';
export const COOLER_ADDRESS_INVALID = 'COOLER_ADDRESS_INVALID';
export const COOLER_PAYMENT_VALID = 'COOLER_PAYMENT_VALID';
export const COOLER_PAYMENT_INVALID = 'COOLER_PAYMENT_INVALID';

// Orders
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const GET_ALL_USER_ORDERS = 'GET_ALL_USER_ORDERS';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
export const LOAD_CURRENT_ORDER = 'LOAD_CURRENT_ORDER';

// Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const CLEAR_SELECTED_PRODUCT = 'CLEAR_SELECTED_PRODUCT';

// Profile
export const GET_PROFILE = 'GET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const PROFILE_ERROR = 'PROFILE_ERROR';
